cloud:
  aws:
    credentials:
      access-key: AKIA4NF34UVFZQV6CQ6Z
      secret-key: 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
    region:
      static: sa-east-1
    stack:
      auto: false

application:
  bucket:
    name: e-manuelbucket

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080